// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHAo4RQ_8e3D2E5X7wM1kGd95JrzPO9s',
    appId: '1:748510442931:web:fd1942bbd0d37e2d9f07c6',
    messagingSenderId: '748510442931',
    projectId: 'learning-flutter-c9484',
    authDomain: 'learning-flutter-c9484.firebaseapp.com',
    storageBucket: 'learning-flutter-c9484.appspot.com',
    measurementId: 'G-3GMLT4P9N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaRgHquKzs57e6kaQuJkEfnjb3g1nYeRA',
    appId: '1:748510442931:android:0707bdd70391fd5f9f07c6',
    messagingSenderId: '748510442931',
    projectId: 'learning-flutter-c9484',
    storageBucket: 'learning-flutter-c9484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5x93jjUIIaLpxJK6SmWR8BYclmZqsGM',
    appId: '1:748510442931:ios:04606fc415cdc2529f07c6',
    messagingSenderId: '748510442931',
    projectId: 'learning-flutter-c9484',
    storageBucket: 'learning-flutter-c9484.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5x93jjUIIaLpxJK6SmWR8BYclmZqsGM',
    appId: '1:748510442931:ios:3a295630b65448fd9f07c6',
    messagingSenderId: '748510442931',
    projectId: 'learning-flutter-c9484',
    storageBucket: 'learning-flutter-c9484.appspot.com',
    iosBundleId: 'com.example.learningFlutter.RunnerTests',
  );
}
